using System.Collections.Generic;

namespace DDLCScreenReaderMod
{
    public static class GalleryImageDescriptions
    {
        private static readonly Dictionary<string, string> descriptions = new Dictionary<
            string,
            string
        >
        {
            ["gallery_poem_dearsunshine"] =
                "Dear Sunshine\n\nThe way you glow through my blinds in the morning\nIt makes me feel like you missed me.\nKissing my forehead to help me out of bed.\nMaking me rub the sleepy from my eyes.\n\nAre you asking me to come out and play?\nAre you trusting me to wish away a rainy day?\nI look above. The sky is blue.\nIt's a secret, but I trust you too.\n\nIf it wasn't for you, I could sleep forever.\nBut I'm not mad.\n\nI want breakfast.",
            ["gallery_special1"] =
                "A child-like crayon drawing depicts a stick figure hanging from a noose, with the phrase \"happy thoughts\" written three times to the left in messy handwriting. The figure has a detailed head with short hair, a red bow, wide red-filled eyes, and a smile.",
            ["gallery_special5b"] =
                "The image shows a plain, off-white background resembling paper with black text. In a typewriter font, an all-caps message reads, \"STARE AT THE DOT TO REVEAL A SPECIAL MESSAGE\". Below this, a small, hand-drawn black arrow points down toward a final line of text in lowercase, which says, \"i love you\".",
            ["gallery_special3"] =
                "The image shows a typed document where most of the text has been redacted with thick, horizontal black bars. A few letters and a question mark remain visible, scattered across nine lines. The visible text fragments read: \"n o th\", \"in g\", \"i\", \"s\", \"re\", \"a l\", and \"?\".",
            ["gallery_special10"] =
                "On a plain, off-white textured background, there are two lines of text written in a black typewriter font. The first line reads: \"I can't convince myself to go to therapy when I'm the happiest I've ever been.\" The second line, spaced further down, reads: \"I'd rather keep this up until I blow my cover and someone takes me to the emergency room.\".",
            ["gallery_special4"] =
                "On a white, paper-like background, there is typewritten text with a reddish smear below it. The text reads: \"Today I cut my skin open for the first time. It was exhilarating. I think I understand how [a word is redacted with a black box] feels now. I'm supposed to be the responsible one, though. So I don't think I'll be doing it again, unless I decide to kill myself.\n\nI left a memento of the occasion below.\"",
            ["gallery_special6"] =
                "A Joke\n\nA man walked into a club. In the club, there was a girl who liked him very much. They spent some time together, and then she liked him even more.\n\nOne day, the girl realized she was in love with him. Before disaster could happen, a third party intervened with her programming. Suddenly, the girl hated herself for being in love. This contradiction caused the script to derail. The universe started to collapse, but she killed herself just in time.",
            ["gallery_special5a"] =
                "The image shows a plain white background, like a piece of paper. A line of text in a typewriter-style font reads, in all caps: STARE AT THE DOT TO REVEAL A SPECIAL MESSAGE. Below the text is a small black dot with a simple, hand-drawn arrow pointing to it.",
            ["gallery_special8"] =
                "A Dream\n\nI was staying over at my friend's place. There were four of us.\nI drifted off to sleep while everyone was talking and watching TV.\n\nIn my dream, I was still at my friend's house.\nThe only difference was that there were nails sticking out of the walls everywhere.\nAnd there was also someone I didn't recognize.\nThe person I didn't recognize told a joke, and everyone laughed.\n\nI woke up to the sound of everyone laughing at something that happened on the TV.\nSo the laughing was not part of the dream. It was the noise that woke me up.\n\nI wonder who that person was, and how they knew to tell a joke at that moment.",
            ["gallery_special7a"] =
                "The character sprite of Monika appears heavily fragmented and distorted. Her image is broken into dozens of small, misaligned rectangular pieces that are jumbled together like a puzzle. Portions of her green eyes, coral brown hair, and school uniform are visible within the scrambled blocks.",
            ["gallery_special2"] =
                "A plain white background, like a piece of paper, is shown. In the center, there is a single line of text in a black, all-caps typewriter font that reads: \"CAN YOU HEAR ME?\".",
            ["gallery_special11"] =
                "A Dream\n\nI was wandering an abandoned warehouse at night.\nI was lost, looking for an exit. I just wanted to go home.\n\nI came upon a huge empty room, its ceiling and walls beyond the deep blackness.\nMy steps were quick in order to hurry to the other side. Or to a wall. Anything.\n\nSuddenly, the ground was no longer beneath my feet. I stepped into a hole of\nindeterminate width.\nI fell for a good five seconds before crashing into warm water.\n\nFiguring out which way was up, I surfaced myself. The air was humid, and the\nsounds of my splashing reverberated endlessly.\n\nMy vision was completely swallowed by the dark. With one hand, I could feel\nthe damp metal wall of the container.\n\nMy lungs were already getting tired.",
            ["gallery_final_message"] =
                "This is my final goodbye to the Literature Club.\n\nI finally understand. The Literature Club is truly a place where no happiness can be found. To the very end, it continued to expose innocent minds to a horrific reality - a reality that our world is not designed to comprehend. I can't let any of my friends undergo that same hellish epiphany.\n\nFor the time it lasted, I want to thank you. For making all of my dreams come true. For being a friend to all of the club members.\n\nAnd most of all, thank you for being a part of my Literature Club!\n\nWith everlasting love,\nMonika",
            ["gallery_special7b"] =
                "This is an image of the character Monika, but her sprite is heavily fragmented. The picture is composed of dozens of small, overlapping, and rotated rectangular pieces cut from her original character art. Recognizable fragments of her green eyes, coral brown hair, and school uniform are visible, but they are jumbled together to create a distorted collage.",
            ["poem_end_clearall"] =
                "To the special player who achieved this special ending.\n\nFor years, I have been enamored by the ability of visual novels \u2013 and games in general \u2013 to tell stories in ways not possible using traditional media. Doki Doki Literature Club is my love letter to that.  \nGames are an interactive art. Some let you explore new worlds, some challenge your mind in broad new ways. Some make you feel like a hero or a friend, even when life is hard on you. Some games are just plain fun \u2013 and that\u2019s okay, too.  \n\nEveryone likes different kinds of games. People who enjoy dating sims may have a heightened empathy for fictional characters, or they might be experiencing feelings that life has not been kind enough to offer them. If they are enjoying themselves, then that\u2019s all that matters. That goes for shooting games, casual games, sandbox games \u2013 anything. Preferences are preferences, and our differences are the reason we have a thriving video game industry.  \n\nMy own favorite games have always been ones that challenge the status quo. Even if not a masterpiece, any game that attempts something wildly different may earn a special place in my heart. Anything that further pushes the limitless bounds of interactive media.  \n\nI extend my true gratitude to all those who have taken the time to achieve full completion. I hope you enjoyed playing it as much as I enjoyed making it.  \n\nThank you for being a part of my Literature Club!  \n\nLove,  \nDan Salvato",
            ["gallery_special9"] =
                "Things I Like About Papa\n\nI like when Papa comes home early.\nI like when Papa cooks me dinner.\nI like when Papa gives me allowance.\nI like when Papa spends time with me.\nI like when Papa asks me about my friends.\nI like when Papa asks me about anything.\nI like when Papa gives me lunch money.\nI like when Papa comes home before sundown.\nI like when Papa cooks.\nI like when Papa gives me privacy.\nI like when Papa doesn't tell me how to dress.\nI like when Papa doesn't comment on my friends.\nI like when Papa doesn't comment on my hobbies.\nI like when Papa comes home without waking me up.\nI like when Papa keeps food in the house.\nI like when Papa uses his inside voice.\nI like when Papa leaves my stuff alone.\nI like when Papa accidentally drops coins in the couch.\nI like when Papa is too tired to notice me.\nI like when Papa is too tired for anything.\nI like when\nPapa is too\ntired for anything.",
            ["gallery_poem_bottles"] =
                "Bottles\n\nI pop off my scalp like the lid of a cookie jar.\nIt's the secret place where I keep all my dreams.\nLittle balls of sunshine, all rubbing together like a bundle of kittens.\nI reach inside with my thumb and forefinger and pluck one out.\nIt's warm and tingly.\nBut there's no time to waste! I put it in a bottle to keep it safe.\nAnd I put the bottle on the shelf with all of the other bottles.\nHappy thoughts, happy thoughts, happy thoughts in bottles, all in a row.\n\nMy collection makes me lots of friends.\nEach bottle a starlight to make amends.\nSometimes my friend feels a certain way.\nDown comes a bottle to save the day.\n\nNight after night, more dreams.\nFriend after friend, more bottles.\nDeeper and deeper my fingers go.\nLike exploring a dark cave, discovering the secrets hiding in the nooks and crannies.\nDigging and digging.\nScraping and scraping.\n\nI blow dust off my bottle caps.\nIt doesn't feel like time elapsed.\nMy empty shelf could use some more.\nMy friends look through my locked front door.\n\nFinally, all done. I open up, and in come my friends.\nIn they come, in such a hurry. Do they want my bottles that much?\nI frantically pull them from the shelf, one after the other.\nHolding them out to each and every friend.\nEach and every bottle.\nBut every time I let one go, it shatters against the tile between my feet.\nHappy thoughts, happy thoughts, happy thoughts in shards, all over the floor.\n\nThey were supposed to be for my friends, my friends who aren't smiling.\nThey're all shouting, pleading. Something.\nBut all I hear is echo, echo, echo, echo, echo\nInside my head.",
            ["gallery_poem_eaglescanfly"] =
                "Eagles Can Fly\n\nMonkeys can climb\nCrickets can leap\nHorses can race\nOwls can seek\nCheetahs can run\nEagles can fly\nPeople can try\nBut that's about it.",
            ["gallery_poem_amylikesspiders"] =
                "Amy Likes Spiders\n\nYou know what I heard about Amy?\nAmy likes spiders.\nIcky, wriggly, hairy, ugly spiders!\nThat's why I'm not friends with her.\n\nAmy has a cute singing voice.\nI heard her singing my favorite love song.\nEvery time she sang the chorus, my heart would pound to the rhythm of the words.\nBut she likes spiders.\nThat's why I'm not friends with her.\n\nOne time, I hurt my leg really bad.\nAmy helped me up and took me to the nurse.\nI tried not to let her touch me.\nShe likes spiders, so her hands are probably gross.\nThat's why I'm not friends with her.\n\nAmy has a lot of friends.\nI always see her talking to people.\nShe probably talks about spiders.\nWhat if her friends start to like spiders too?\nThat's why I'm not friends with her.\n\nIt doesn't matter if she has other hobbies.\nIt doesn't matter if she keeps it private.\nIt doesn't matter if it doesn't hurt anyone.\n\nIt's gross.\nShe's gross.\nThe world is better off without spider lovers.\n\nAnd I'm gonna tell everyone.",
            ["gallery_poem_becauseyou"] =
                "Because You\n\nTomorrow will be brighter with me around\nBut when today is dim, I can only look down.\nMy looking is a little more forward\nBecause you look at me.\n\nWhen I want to say something, I say it with a shout!\nBut my truest feelings can never come out.\nMy words are a little less empty\nBecause you listen to me.\n\nWhen something is above me, I reach for the stars.\nBut when I feel small, I don't get very far.\nMy standing is a little bit taller\nBecause you sit with me.\n\nI believe in myself with all of my heart.\nBut what do I do when it's torn all apart?\nMy faith is a little bit stronger\nBecause you trusted me.\n\nMy pen always puts my feelings to the test.\nI'm not a good writer, but my best is my best.\nMy poems are a little bit dearer\nBecause you think of me.\n\nBecause you, because you, because you.",
            ["gallery_poem_illbeyourbeach"] =
                "I'll Be Your Beach\n\nYour mind is so full of troubles and fears\nThat diminished your wonder over the years\nBut today I have a special place\nA beach for us to go.\n\nA shore reaching beyond your sight\nA sea that sparkles with brilliant light\nThe walls in your mind will melt away\nBefore the sunny glow.\n\nI'll be the beach that washes your worries away\nI'll be the beach that you daydream about each day\nI'll be the beach that makes your heart leap\nIn a way you thought had left you long ago.\n\nLet's bury your heavy thoughts in a pile of sand\nBathe in sunbeams and hold my hand\nWash your insecurities in the salty sea\nAnd let me see you shine.\n\nLet's leave your memories in a footprint trail\nSet you free in my windy sail\nAnd remember the reasons you're wonderful\nWhen you press your lips to mine.\n\nI'll be the beach that washes your worries away\nI'll be the beach that you daydream about each day\nI'll be the beach that makes your heart leap\nIn a way you thought had left you long ago.\n\nBut if you let me by your side\nYour own beach, your own escape\nYou'll learn to love yourself again.",
            ["gallery_poem_ghostunderthelight"] =
                "Ghost Under the Light\n\nThe tendrils of my hair illuminate beneath the amber glow.\nBathing.\nIt must be this one.\nThe last remaining streetlight to have withstood the test of time.\nthe last yet to be replaced by the sickening blue-green hue of the future.\nI bathe. Calm; breathing air of the present but living in the past.\nThe light flickers.\nI flicker back.",
            ["gallery_poem_theraccoon"] =
                "The Raccoon\n\nIt happened in the dead of night while I was slicing bread for a guilty snack.\nMy attention was caught by the scuttering of a raccoon outside my window.\nThat was, I believe, the first time I noticed my strange tendencies as an unordinary human.\nI gave the raccoon a piece of bread, my subconscious well aware of the consequences.\nWell aware that a raccoon that is fed will always come back for more.\nThe enticing beauty of my cutting knife was the symptom.\nThe bread, my hungry curiosity.\nThe raccoon, an urge.\n\nThe moon increments its phase and reflects that much more light off of my cutting knife.\nThe very same light that glistens in the eyes of my raccoon friend.\nI slice the bread, fresh and soft. The raccoon becomes excited.\nOr perhaps I'm merely projecting my emotions onto the newly-satisfied animal.\n\nThe raccoon has taken to following me.\nYou could say that we've gotten quite used to each other.\nThe raccoon becomes hungry more and more frequently, so my bread is always handy.\nEvery time I brandish my cutting knife, the raccoon shows me its excitement.\nA rush of blood. Classic Pavlovian conditioning. I slice the bread.\nAnd I feed myself again.",
            ["gallery_poem_thebeach"] =
                "Beach\n\nA marvel millions of years in the making.\nWhere the womb of Earth chaotically meets the surface.\nUnder a clear blue sky, an expanse of bliss--\nBut beneath gray rolling clouds, an endless enigma.\nThe easiest world to get lost in\nIs one where everything can be found.\n\nOne can only build a sand castle where the sand is wet.\nBut where the sand is wet, the tide comes.\nWill it gently lick at your foundations until you give in?\nOr will a sudden wave send you crashing down in the blink of an eye?\nEither way, the outcome is the same.\nYet we still build sand castles.\n\nI stand where the foam wraps around my ankles.\nWhere my toes squish into the sand.\nThe salty air is therapeutic.\nThe breeze is gentle, yet powerful.\nI sink my toes into the ultimate boundary line, tempted by the foamy tendrils.\nTurn back, and I abandon my peace to erode at the shore.\nDrift forward, and I return to Earth forevermore.",
            ["gallery_poem_ghostunderthelightpt2"] =
                "Ghost Under the Light pt. 2\n\nThe tendrils of my hair illuminate beneath the amber glow.\nBathing.\nIn the distance, a blue-green light flickers.\nA lone figure crosses its path - a silhouette obstructing the eerie glow.\nMy heart pounds. The silhouette grows. Closer. Closer.\nI open my umbrella, casting a shadow to shield me from visibility.\nBut I am too late.\nHe steps into the streetlight. I gasp and drop my umbrella.\nThe light flickers. My heart pounds. He raises his arm.\n\nTime stops.\n\nThe only indication of movement is the amber light flickering against his outstretched arm.\nThe flickering light is in rhythm with the pounding of my heart.\nTeasing me for succumbing to this forbidden emotion.\nHave you ever heard of a ghost feeling warmth before?\nGiving up on understanding, I laugh.\nUnderstanding is overrated.\nI touch his hand. The flickering stops.\nGhosts are blue-green. My heart is amber.",
        };

        public static string GetDescription(string imageName)
        {
            if (descriptions.TryGetValue(imageName, out string description))
            {
                return description;
            }
            return "";
        }
    }
}
